# Generated by Django 3.2.9 on 2022-01-16 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='my_social_page',
            field=models.TextField(blank=True, verbose_name='ссылка на социальную сеть'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 18, 19, 27, 36, 270517, tzinfo=utc)),
        ),
    ]
